### PR TITLE
Add psr/log 2.0 and 3.0

### PR DESCRIPTION
**Pull request by JanoschOltmanns**
Currently the `psr/log` dependency is set to `^1.1` Another package I want to use has it set to `^2.0`. Unfortunately, this causes conflicts. Therefore, I propose to allow `^2.0` here as well. The signatures look identical, the tests ran through and the standard should also have no changes.

Or are there any reasons for `^1.1` that I don't see?

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by Toflar** [comment]
There are about 15 tests failing with this change. Let me check why the CI does not run on PRs.

**Review by Toflar — CHANGES_REQUESTED** [review]
There you go, the tests do not run through ;)

**Comment by JanoschOltmanns** [comment]
Thanks. I will have a look at it.

**Comment by Toflar** [comment]
Also, there's a v3 too apparently.

**Comment by Toflar** [comment]
I took the liberty to check the differences and push directly. Apparently there's no `TestLogger` anymore so I resorted to `beste/psr-testlogger` but this now does not allow < PHP 8.1 🙄

**Comment by JanoschOltmanns** [comment]
I want to test with https://github.com/php-fig/log-util

**Comment by JanoschOltmanns** [comment]
https://github.com/php-fig/log-util is not on packagist 🙈 So I tried another package. Looks good "on my machine". But still waiting for the other php versions.

**Comment by Toflar** [comment]
We should use https://github.com/php-fig/log-test ;)

**Comment by Toflar** [comment]
Sorry for the hassle, at least now we know all the PSR log testing utilities out there :D I'm going to tag a new release in a minute. Thank you @JanoschOltmanns!

**Pull request merged**
